### ISSUE TITLE
Timer reporting to elasticsearch failes

### ISSUE THREAD

**Issue by andiikaa** [IoTUDresden/feedback-service#3]
Look in LoopMetricsAspect#trackIterationSuccessFor
(Fork https://github.com/andiikaa/feedback-service)

`elasticsearch | [2017-08-04 15:30:23,775][DEBUG][action.bulk              ] [Dr. John Grey] [mapek-2017-08][3] failed to execute bulk item (index) index {[mapek-2017-08][timer][AV2t3nWcTHp3Pt8MoO6h], source[{"name":"workflow.Workflow_MoveTurtleRemote._5bkv0HawEeexVf8Jvgvr3w_Instance_2.3415.plan.time","@timestamp":"2017-08-04T15:30:23.000+0000","count":1,"max":7481.519375999999,"mean":7481.519375999999,"min":7481.519375999999,"p50":7481.519375999999,"p75":7481.519375999999,"p95":7481.519375999999,"p98":7481.519375999999,"p99":7481.519375999999,"p999":7481.519375999999,"stddev":0.0,"m15_rate":0.003878182897443776,"m1_rate":0.001008172795881715,"m5_rate":0.002490087154587789,"mean_rate":0.010496886683383671,"duration_units":"milliseconds","rate_units":"calls/second"}]}
elasticsearch | org.elasticsearch.index.mapper.MapperParsingException: failed to parse [@timestamp]
elasticsearch |         at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:411)
elasticsearch |         at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:706)
elasticsearch |         at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
elasticsearch |         at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
elasticsearch |         at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
elasticsearch |         at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:465)
elasticsearch |         at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:418)
elasticsearch |         at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:148)
elasticsearch |         at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
elasticsearch |         at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
elasticsearch |         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
elasticsearch |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
elasticsearch |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
elasticsearch |         at java.lang.Thread.run(Thread.java:745)
elasticsearch | Caused by: java.lang.NumberFormatException: For input string: "2017-08-04T15:30:23.000+0000"
elasticsearch |         at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
elasticsearch |         at java.lang.Long.parseLong(Long.java:589)
elasticsearch |         at java.lang.Long.parseLong(Long.java:631)
elasticsearch |         at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
elasticsearch |         at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:288)
elasticsearch |         at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:239)
elasticsearch |         at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:401)
`

**Comment by andiikaa** [comment]
Happens, if different timestamp formats are delivered to elasticsearch (e.g. long millis and "2017-08-01T13:30:15").
To fix this use same format or a different index.
